name : cloudmining.github.io
brand : CloudMining
description : CloudMining site
keyword : 
url : https://cloudmining.github.io/
email : info@cloudmining.one
twitter : CloudMining
github : CloudMining
author : CloudMining
year : 2017
markdown : kramdown
exclude :
  - node_modules
